modLoader="javafml" #mandatory

loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"

[[mods]] #mandatory

modId="ads" #mandatory

version="1.0" #mandatory

displayName="ads" #mandatory

credits="Thanks for this example mod goes to Java" #optional

authors="Angelo, Daniel, & Steven" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
ads
'''

[[dependencies.ads]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[44,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.ads]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.ads]]
modId="geckolib"
mandatory=true
versionRange="[4,)"
ordering="NONE"
side="BOTH"